/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as PagesSlugRouteImport } from './routes/pages.$slug'
import { Route as AuthenticatedWishlistRouteImport } from './routes/_authenticated/wishlist'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminThemeRouteImport } from './routes/_authenticated/admin/theme'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin/products'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as AuthenticatedAdminPagesRouteImport } from './routes/_authenticated/admin/pages'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin/orders'
import { Route as AuthenticatedAdminCouponsRouteImport } from './routes/_authenticated/admin/coupons'
import { Route as AuthenticatedAdminChatRouteImport } from './routes/_authenticated/admin/chat'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin/categories'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWishlistRoute = AuthenticatedWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminThemeRoute = AuthenticatedAdminThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPagesRoute = AuthenticatedAdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCouponsRoute =
  AuthenticatedAdminCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminChatRoute = AuthenticatedAdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/account': typeof AuthenticatedAccountRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/chat': typeof AuthenticatedAdminChatRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/theme': typeof AuthenticatedAdminThemeRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/chat': typeof AuthenticatedAdminChatRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/theme': typeof AuthenticatedAdminThemeRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/wishlist': typeof AuthenticatedWishlistRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/chat': typeof AuthenticatedAdminChatRoute
  '/_authenticated/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/theme': typeof AuthenticatedAdminThemeRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/shop'
    | '/sitemap.xml'
    | '/admin'
    | '/account'
    | '/checkout'
    | '/wishlist'
    | '/pages/$slug'
    | '/product/$slug'
    | '/admin/categories'
    | '/admin/chat'
    | '/admin/coupons'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/theme'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/shop'
    | '/sitemap.xml'
    | '/account'
    | '/checkout'
    | '/wishlist'
    | '/pages/$slug'
    | '/product/$slug'
    | '/admin/categories'
    | '/admin/chat'
    | '/admin/coupons'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/theme'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/shop'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/account'
    | '/_authenticated/checkout'
    | '/_authenticated/wishlist'
    | '/pages/$slug'
    | '/product/$slug'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/chat'
    | '/_authenticated/admin/coupons'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/pages'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/theme'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PagesSlugRoute: typeof PagesSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wishlist': {
      id: '/_authenticated/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof AuthenticatedWishlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/theme': {
      id: '/_authenticated/admin/theme'
      path: '/theme'
      fullPath: '/admin/theme'
      preLoaderRoute: typeof AuthenticatedAdminThemeRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pages': {
      id: '/_authenticated/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AuthenticatedAdminPagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/coupons': {
      id: '/_authenticated/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AuthenticatedAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/chat': {
      id: '/_authenticated/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AuthenticatedAdminChatRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminChatRoute: typeof AuthenticatedAdminChatRoute
  AuthenticatedAdminCouponsRoute: typeof AuthenticatedAdminCouponsRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminPagesRoute: typeof AuthenticatedAdminPagesRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminThemeRoute: typeof AuthenticatedAdminThemeRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
    AuthenticatedAdminChatRoute: AuthenticatedAdminChatRoute,
    AuthenticatedAdminCouponsRoute: AuthenticatedAdminCouponsRoute,
    AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
    AuthenticatedAdminPagesRoute: AuthenticatedAdminPagesRoute,
    AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
    AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminThemeRoute: AuthenticatedAdminThemeRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedWishlistRoute: typeof AuthenticatedWishlistRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedWishlistRoute: AuthenticatedWishlistRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PagesSlugRoute: PagesSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
